// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPermission() {
  return window['go']['main']['App']['CheckPermission']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function StartClicking(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartClicking'](arg1, arg2, arg3, arg4, arg5);
}

export function StopClicking() {
  return window['go']['main']['App']['StopClicking']();
}
