// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPermission():Promise<boolean>;

export function Greet(arg1:string):Promise<string>;

export function StartClicking(arg1:number,arg2:string,arg3:string,arg4:string,arg5:number):Promise<void>;

export function StopClicking():Promise<void>;
